-- Transfer Portal Intelligence Platform Tables

CREATE TABLE IF NOT EXISTS `transfer_portal_athletes` (
  `id` int AUTO_INCREMENT NOT NULL,
  `name` varchar(255) NOT NULL,
  `sport` varchar(100) NOT NULL,
  `position` varchar(100),
  `year` varchar(50),
  `heightInches` int,
  `weightPounds` int,
  `hometown` varchar(255),
  `homeState` varchar(2),
  `highSchool` varchar(255),
  `previousSchool` varchar(255) NOT NULL,
  `previousConference` varchar(100),
  `previousDivision` varchar(50),
  `portalEntryDate` date NOT NULL,
  `portalStatus` enum('entered','committed','withdrawn') NOT NULL DEFAULT 'entered',
  `newSchool` varchar(255),
  `commitmentDate` date,
  `expectedDecisionDate` date,
  `on3Rating` decimal(5,2),
  `on3Rank` int,
  `twoFourSevenRating` decimal(5,4),
  `twoFourSevenRank` int,
  `rivalsRating` decimal(5,2),
  `rivalsRank` int,
  `espnRating` int,
  `espnRank` int,
  `compositeRating` decimal(5,2),
  `compositeRank` int,
  `stars` int,
  `nilValuation` decimal(10,2),
  `nilDeals` int DEFAULT 0,
  `estimatedNilEarnings` decimal(10,2),
  `stats` json,
  `gpa` decimal(3,2),
  `testScores` json,
  `eligibilityYears` int,
  `profileImageUrl` varchar(500),
  `highlightReelUrl` varchar(500),
  `hudlUrl` varchar(500),
  `twitterHandle` varchar(100),
  `instagramHandle` varchar(100),
  `tiktokHandle` varchar(100),
  `twitterFollowers` int,
  `instagramFollowers` int,
  `tiktokFollowers` int,
  `interestedSchools` json,
  `officialVisits` json,
  `offers` json,
  `dataSource` json,
  `lastScraped` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `verified` enum('yes','no') NOT NULL DEFAULT 'no',
  `featured` enum('yes','no') NOT NULL DEFAULT 'no',
  `premium` enum('yes','no') NOT NULL DEFAULT 'no',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `transfer_portal_athletes_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `school_subscriptions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `schoolName` varchar(255) NOT NULL,
  `contactName` varchar(255) NOT NULL,
  `contactEmail` varchar(320) NOT NULL,
  `contactPhone` varchar(20),
  `tier` enum('free','pro','elite','enterprise') NOT NULL DEFAULT 'free',
  `monthlyPrice` decimal(10,2),
  `billingCycle` enum('monthly','annual') NOT NULL DEFAULT 'monthly',
  `stripeCustomerId` varchar(255),
  `stripeSubscriptionId` varchar(255),
  `athleteViewsLimit` int,
  `athleteViewsUsed` int NOT NULL DEFAULT 0,
  `searchesLimit` int,
  `searchesUsed` int NOT NULL DEFAULT 0,
  `realTimeAlerts` enum('yes','no') NOT NULL DEFAULT 'no',
  `aiMatching` enum('yes','no') NOT NULL DEFAULT 'no',
  `apiAccess` enum('yes','no') NOT NULL DEFAULT 'no',
  `exportData` enum('yes','no') NOT NULL DEFAULT 'no',
  `status` enum('active','paused','cancelled','trial') NOT NULL DEFAULT 'trial',
  `trialEndsAt` timestamp,
  `subscriptionStartDate` timestamp,
  `subscriptionEndDate` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `school_subscriptions_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `athlete_views` (
  `id` int AUTO_INCREMENT NOT NULL,
  `schoolSubscriptionId` int NOT NULL,
  `athleteId` int NOT NULL,
  `viewedBy` varchar(255),
  `viewType` enum('profile','video','stats','contact') NOT NULL,
  `viewedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `athlete_views_id` PRIMARY KEY(`id`),
  CONSTRAINT `athlete_views_schoolSubscriptionId_school_subscriptions_id_fk` FOREIGN KEY (`schoolSubscriptionId`) REFERENCES `school_subscriptions`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `athlete_views_athleteId_transfer_portal_athletes_id_fk` FOREIGN KEY (`athleteId`) REFERENCES `transfer_portal_athletes`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `transfer_portal_alerts` (
  `id` int AUTO_INCREMENT NOT NULL,
  `schoolSubscriptionId` int NOT NULL,
  `sport` varchar(100),
  `positions` json,
  `minRating` decimal(5,2),
  `maxRating` decimal(5,2),
  `states` json,
  `previousDivision` varchar(50),
  `minNilValuation` decimal(10,2),
  `alertName` varchar(255) NOT NULL,
  `alertType` enum('email','sms','push','all') NOT NULL DEFAULT 'email',
  `frequency` enum('instant','daily','weekly') NOT NULL DEFAULT 'instant',
  `active` enum('yes','no') NOT NULL DEFAULT 'yes',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `transfer_portal_alerts_id` PRIMARY KEY(`id`),
  CONSTRAINT `transfer_portal_alerts_schoolSubscriptionId_school_subscriptions_id_fk` FOREIGN KEY (`schoolSubscriptionId`) REFERENCES `school_subscriptions`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `ai_match_recommendations` (
  `id` int AUTO_INCREMENT NOT NULL,
  `schoolSubscriptionId` int NOT NULL,
  `athleteId` int NOT NULL,
  `matchScore` decimal(5,2) NOT NULL,
  `confidence` enum('low','medium','high','very_high') NOT NULL,
  `matchReasons` json,
  `aiAnalysis` text,
  `schoolNeed` varchar(255),
  `athleteFit` text,
  `status` enum('new','viewed','contacted','passed','committed') NOT NULL DEFAULT 'new',
  `feedback` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `ai_match_recommendations_id` PRIMARY KEY(`id`),
  CONSTRAINT `ai_match_recommendations_schoolSubscriptionId_school_subscriptions_id_fk` FOREIGN KEY (`schoolSubscriptionId`) REFERENCES `school_subscriptions`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ai_match_recommendations_athleteId_transfer_portal_athletes_id_fk` FOREIGN KEY (`athleteId`) REFERENCES `transfer_portal_athletes`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `transfer_portal_analytics` (
  `id` int AUTO_INCREMENT NOT NULL,
  `date` date NOT NULL,
  `sport` varchar(100) NOT NULL,
  `totalEntered` int NOT NULL DEFAULT 0,
  `totalCommitted` int NOT NULL DEFAULT 0,
  `totalWithdrawn` int NOT NULL DEFAULT 0,
  `positionBreakdown` json,
  `divisionBreakdown` json,
  `avgRating` decimal(5,2),
  `topRatedAthletes` json,
  `avgNilValuation` decimal(10,2),
  `totalNilValue` decimal(12,2),
  `trendDirection` enum('up','down','stable'),
  `percentChange` decimal(5,2),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `transfer_portal_analytics_id` PRIMARY KEY(`id`)
);
